### ISSUE TITLE
Wiki claims to be "open" but is restricted to editing by collaborators

### ISSUE THREAD

**Issue by per1234** [ATMakersOrg/OpenIKeys#1]
From https://github.com/ATMakersOrg/OpenIKeys/wiki:
>This is an open Wiki - please feel free to edit to add your own IntelliKeys-specific information including how you'd like to continue using the devices.

However, the wiki is set to only be editable by collaborators so the above statement is incorrect.

Proposals to resolve this:
- Set the wiki to allow editing by anyone: Settings > Restrict editing to collaborators only (uncheck)

**OR**

- Remove the statement "This is an open Wiki". That statement also occurs on this (duplicate) page:
https://github.com/ATMakersOrg/OpenIKeys/wiki/OpenIKeys---An-Open-Source-driver-for-the-IntelliKeys-Accessible-Keyboards

**Comment by ATMakersBill** [comment]
I have enabled editing. Please contribute positively
