### ISSUE TITLE
Classroom Suite Source Code

### ISSUE THREAD

**Issue by MGlaab** [ATMakersOrg/OpenIKeys#9]
I emailed back and forth with a sales rep at AbleNet. They informed me that the source code for Classroom Suite and Overlay Maker are open source and available through ATMakers. I'm not able to contact ATMakers through Facebook. I'm just wondering where the repos are for those programs? Thanks.

**Comment by wernedat** [comment]
The best contact would be Bill Binko - bill@atmakers.org


*Elisa*




*---------------------------------------Elisa Wern M.Ed., OTR/L, ATPLead
Occupational Therapist &Local Assistive Technology Specialist*
*RESNA Certified Assistive Technology Specialist*


* Alachua County Public SchoolsManning Center/ESE & Student Services*
*1817 E University Avenue*
*Gainesville, FL 32601*


*(352) 955-7671 x 1629(844) 410-6813 ESE Fax Attn: Elisa Wern*
*werned@gm.sbac.edu* <werned@gm.sbac.edu>
